# Generated by Django 6.0.3 on 2026-03-27 08:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('initial_balance_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('initial_balance_usd', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('CASH', 'Naqd'), ('PLASTIC', 'Plastik'), ('BANK', 'Bank')], max_length=10)),
                ('currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('initial_balance_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('initial_balance_usd', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], max_length=3)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.financialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.DecimalField(decimal_places=2, max_digits=16)),
                ('reason', models.CharField(choices=[('sale', 'Sotuv'), ('expenditure', 'Xarajat'), ('supplier_payment', "Yetkazib beruvchi to'lovi"), ('agent_payment', "Agent to'lovi"), ('reversal', 'Teskari qaytarish')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.financialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AgentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], max_length=3)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.agent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.financialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('product_type', models.CharField(choices=[('TICKET', 'Aviabilet'), ('UMRA', 'Umra'), ('TOUR', 'Turi')], max_length=10)),
                ('destination', models.CharField(max_length=200)),
                ('commentary', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('acquired_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('acquired_currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], max_length=3)),
                ('customer_type', models.CharField(choices=[('AGENT', 'Agent'), ('WALKIN', 'Keluvchi')], max_length=10)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_passport', models.CharField(blank=True, max_length=50)),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('sold_currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], max_length=3)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.agent')),
                ('financial_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.financialaccount')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_sales', to=settings.AUTH_USER_MODEL)),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], max_length=3)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.financialaccount')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier')),
            ],
        ),
    ]
