# Generated by Django 6.0.3 on 2026-04-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
