# Generated by Django 6.0.3 on 2026-04-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_financialaccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
